#:schema node_modules/wrangler/config-schema.json
name = "seo"
main = "src/index.js"
compatibility_date = "2025-01-24"

routes = [
  "yusong.tw/*"
]

# Exclude common static file paths using wrangler's ignore rules
[[rules]]
globs = ["**/*.js", "**/*.css", "**/*.png", "**/*.jpg", "**/*.svg", "**/*.ico", "**/*.txt"]
type = "static"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true
