#:schema node_modules/wrangler/config-schema.json
name = "blog-og-img"
main = "src/index.js"
compatibility_date = "2025-01-24"
minify = true

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true
