name: deploy-worker

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "src/pages/**/index.md"
      - "src/pages/**/index.meta.js"
      - "cloudflare-workers/seo/src/index.js"
# on:
#   pull_request:
#     types: [opened, reopened, synchronize]

concurrency:
  group: "deploy-worker"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Generate routes data
        run: npm run gen:routeData

      - name: Build & Deploy SEO Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: cloudflare-workers/seo
          preCommands: npm run build
