name: generate-article

on:
  workflow_dispatch:
    inputs:
      path:
        description: "File path"
        required: true
        default: "/src/pages/article"
        type: string
      title:
        description: "Article title"
        required: true
        type: string
      description:
        description: "Article description"
        required: true
        type: string
      tags:
        description: "Article tags (comma separated)"
        required: false
        type: string
      series:
        description: "Article tags (comma separated)"
        required: false
        type: string
      index:
        description: "Article tags (comma separated)"
        required: false
        type: string
      content:
        description: "Article content"
        required: true
        type: string

jobs:
  generate-article:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.REPO_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Generate article
        run: node ./scripts/generateArticle.js
        env:
          INPUT_PATH: ${{ github.event.inputs.path }}
          INPUT_TITLE: ${{ github.event.inputs.title }}
          INPUT_DESCRIPTION: ${{ github.event.inputs.description }}
          INPUT_TAGS: ${{ github.event.inputs.tags }}
          INPUT_SERIES: ${{ github.event.inputs.series }}
          INPUT_INDEX: ${{ github.event.inputs.index }}
          INPUT_CONTENT: ${{ github.event.inputs.content }}

      - name: Commit and Push
        run: |
          TIMESTAMP=$(date +"%Y%m%d%H%M%S")
          BRANCH_NAME="workflow-pr-${TIMESTAMP}"

          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"

          git checkout -b "$BRANCH_NAME"
          git add .
          git commit -m "docs: generate article [${{ github.event.inputs.title }}]"
          git push origin "$BRANCH_NAME"

      - name: Create Pull Request
        uses: actions/github-script@v7
        with:
          script: |
            const title = `docs: generate article [${{ github.event.inputs.title }}]`;
            const { data: pr } = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              head: process.env.BRANCH_NAME,
              base: "main",
              body: "This PR was automatically generated by the workflow."
            });
            console.log(`Pull request created: ${pr.html_url}`);
