name: gpt-translate

on:
  issue_comment:
    types: [created]

jobs:
  gpt_translate:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/gt') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run GPT Translate
        uses: 3ru/gpt-translate@master
        with:
          apikey: ${{ secrets.OPENAI_API_KEY }}
