name: render-md-mermaid

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "**.md"

jobs:
  render-md-mermaid:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Render images for every Mermaid diagram in all Markdown files (*.md) in the repo
        uses: nielsvaneck/render-md-mermaid@v3

      - name: Commit rendered png and svg files
        run: ls -l src/pages/article/tech/lazy
