name: render-md-mermaid

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "**.md"

jobs:
  render-md-mermaid:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_TOKEN }}
          ref: ${{ github.head_ref }}

      - name: Render images for every Mermaid diagram in all Markdown files (*.md) in the repo
        uses: nielsvaneck/render-md-mermaid@v3

      - name: Commit rendered png and svg files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: "*[.svg,.png]"
          commit_user_name: "${GITHUB_ACTOR}"
          commit_user_email: "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
          commit_message: "chore: automatically rendered mermaid diagrams"
