name: update-frontmatter

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: "update-frontmatter"
  cancel-in-progress: true

jobs:
  update-frontmatter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }} # Ensures checkout on PR branch
          repository: ${{ github.event.pull_request.head.repo.full_name }} # Ensures correct repo for forks
          token: ${{ secrets.REPO_TOKEN }}

      - name: Check for changes in src/
        id: check_changes
        run: |
          if git diff --name-only origin/main...HEAD | grep -q '^src/.*/index\.md$'; then
            echo "Changes detected in src/, continuing workflow."
            echo "changed=true" >> $GITHUB_ENV
          else
            echo "No changes in src/, stopping workflow."
            exit 0
          fi

      - name: Setup Node.js
        if: env.changed == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Update modifiedAt in Markdown files
        run: node ./scripts/updateArticleFrontmatter.js

      - name: Check for changes
        id: git_diff
        run: |
          git status --porcelain | grep -E '\.(md)$' && echo "changed=1" >> $GITHUB_OUTPUT || echo "changed=0"

      - name: Commit changes
        if: ${{ steps.git_diff.outputs.changed == 1 }}
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.number }}
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -m "chore: automatically update articles modifiedAt"
          git push
          gh pr comment ${{ env.PR_NUMBER }} --body "🤖 update articles modifiedAt, commit: $(git rev-parse --short HEAD)."
